config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    member do
      get 'categorize'
      get 'associate'
    end
  end
  resources :answers do
    member do
      get 'automatic'
    end
  end
  resources :intents
  resources :contexts
  resources :skus
  resources :context_categories
  resources :conversations do
    collection do
      get 'webhook'
    end
  end
  get 'static_pages/chat'

  resources :brands
  resources :products
  resources :product_types
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :users

  #get 'users/new'

  root to: 'visitors#index'
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :logged_in_user

  def index
  	@product_types = ProductType.where("active = ?", true)
  end

  def show
  	@product_type = ProductType.find(params[:id])
  	@products = @product_type.products
  end

  def new
  	@product_type = ProductType.new
  end

  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to product_types_path, notice: 'Product Type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(:name, :description, :active)
    end

end

app/views/product_types/_form.html.erb
<%= form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows:7, cols:75 %>
  </div>
  <div class="field">
    Active <%= f.check_box :active %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>
<br />

app/views/product_types/index.html.erb
<h1>Product Types</h1>
<br />

<table>
  <thead>
    <tr>
      <th align="left" valign="top">Name&nbsp;&nbsp;&nbsp;</th>
      <th align="left" valign="top">Description&nbsp;&nbsp;&nbsp;</th>
      <th align="left" colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |type| %>
      <tr>
        <td valign="top"><%= link_to "#{type.name}", type %>&nbsp;&nbsp;&nbsp;</td>
        <td valign="top"><%= type.description %>&nbsp;&nbsp;&nbsp;</td>
        <td valign="top"><%= link_to "Add Products", product_type_path(type) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<h1>PRODUCT TYPE: <%= @product_type.name %></h1>
<br />
<p>
<% if @products.size == 0 %>
  You have not added any Products to this Product Type.<br /><br />
  <%= link_to "Add new Product to Product Type: #{@product_type.name}", new_product_path(:product_type_id => @product_type.id) %>
<% else %>
  <table>
  <thead>
    <tr>
      <th>Product</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Description</th>
      <th></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to "#{product.name}", product_path(product)  %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= product.description %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to(image_tag("plus.png", :alt => "add", :title => "Add brand"), new_brand_path(:product_id => product.id)) %></td>
        <td>&nbsp;</td>
        <!--td><%#= link_to(image_tag("pencil.png", :alt => "edit", :title => "Edit product"), edit_product_path(:product_id => product.id)) %></td-->
        <td><%= link_to(image_tag("pencil.png", :alt => "edit", :title => "Edit product"), edit_product_path(product)) %></td>
        <td>&nbsp;</td>
        <td><%= link_to(image_tag("delete.png", :alt => "delete", :title => "Delete product"), product, method: :delete, data: { confirm: 'Are you sure?' }) %>
      </tr>
    <% end %>
  </tbody>
  </table>
  <br />
  <%= link_to "Add new Product to Product Type: #{@product_type.name}", new_product_path(:product_type_id => @product_type.id) %>
<% end %>

<br /><br /><%= link_to 'Back', product_types_path %>