config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    member do
      get 'categorize'
      get 'associate'
    end
  end
  resources :answers do
    member do
      get 'automatic'
    end
  end
  resources :intents
  resources :contexts
  resources :skus
  resources :context_categories
  resources :conversations do
    collection do
      get 'webhook'
    end
  end
  get 'static_pages/chat'

  resources :brands
  resources :products
  resources :product_types
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :users

  #get 'users/new'

  root to: 'visitors#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :categorized_message
end

app/controllers/messages_controller.rb
require './app/operations/services/persistence/persist_message'
require './app/operations/processing/process_message'

class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @categorized_message = CategorizedMessage.where("message_id = ?", @message.id).first
    @intent = Intent.find(@categorized_message.intent_id)
    @answers = Answer.where("intent_id = ? and automatic <> ?", @intent.id, true).order("upvotes desc")
    if @answers.size > 0
      @top_answer = @answers.first
    else
      @top_answer = Answer.where("intent_id = ?", @intent.id).first
    end
    @ordered_answers = []
    count = 1
    @answers.each do |answer|
      if count > 1
        @ordered_answers << answer
      else
        count += 1
      end
    end
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.body = params[:message][:body].downcase
    persist_message ||= PersistMessage.new
    @message = persist_message.execute(@message)

    respond_to do |format|
      if !@message.nil?
        process_message ||= ProcessMessage.new
        result = process_message.execute(@message.body)
        if result["intent_id"] == 0
          format.html { redirect_to categorize_message_path(@message) }
          format.json { render :show, status: :created, location: @message }
        else
          format.html { redirect_to result["message"], notice: 'Message intent found.' }
          format.json { render :show, status: :created, location: @message }
        end
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def categorize
    @message = Message.find(params[:id])
    @intents = Intent.where("active = ?", true)
  end

  def associate
    @message = Message.find(params[:id])
    @intent = Intent.find(params[:intent_id])
    if !@intent.nil?
      categorized_message = CategorizedMessage.new
      categorized_message.message_id = @message.id
      categorized_message.intent_id = @intent.id
      categorized_message.save
      @answers = Answer.where("intent_id = ?", @intent.id)
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:conversation_id, :intent_id, :body)
    end
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited User's message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :body, rows:10, cols:70 %>
  </div>
  <div class="actions">
    <%= f.submit "Process" %>
  </div>
<% end %>

app/views/messages/associate.html.erb
<br />
<font size="6"><strong>Bot Says</strong></font>
<br /><br />
<% if @answers.size > 0 %>
  <font size="4">
  I found these answers for the detected intent <em>(<%= @intent.name %>)</em>; please select the most appropriate answer to the user's message
  <br /><br />
  <strong>"<%= @message.body %>"</strong>
  </font>
  <br /><br />
  <font size="5">Select the answer:</font>
  <br /><br />
  <ul>
  <% @answers.each do |answer| %>
    <li><em><font size="3"><%= link_to "#{answer.reply}", answer_path(answer) %></font></em>&nbsp;&nbsp;&nbsp;(Upvotes: <%= answer.upvotes %>, Downvotes: <%= answer.downvotes %>)</li>
    <br />
  <% end %>
  </ul>
<% else %>
  <font size="4">I could not find any answers for the detected intent -- <em><%= @intent.name %></em>.
  <br /><br />
  Please <%= link_to "add an answer", new_answer_path(:intent_id => @intent.id) %> for <em><%= @intent.name %></em>.</font>
<% end %>

app/views/messages/categorize.html.erb
<br />
<font size="6"><strong>Bot Says</strong></font>
<br />
<font size="5">I've received this message and could not find its intent:</font>
<br />
<h3><em>"<%= @message.body %>"</em></h3>
<br />
<font size="3">Please help me associate the above message with one of the intents by clicking on the appropriate intent below:</font>
<br /><br />
<% @intents.each do |intent| %>
  <font size="5"><%= link_to "#{intent.name}", associate_message_path(@message, :intent_id => intent.id)  %><font size="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Conversation</th>
      <th>Intent</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.conversation_id %></td>
        <td><%= message.intent_id %></td>
        <td><%= message.body %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>User Says</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<h1>Bot Says</h1>
<br />
<font size="4">I was able to associate user's message <em><%= @message.body %></em> with this intent:</font>
<br />
<font size="5"><%= @intent.name %></font>
<br /><br />
<font size="4">The most appropriate answer to this message might be:</font> <font size="5"><em><%= link_to "#{@top_answer.reply}", answer_path(@top_answer) %></em></font>.
<font size="4"><% if @top_answer.upvotes > 0 %>I chose that answer because it has the most upvotes -- <%= @top_answer.upvotes %> so far.<% end %> Please click on it if you think it's the most appropriate answer. If you agree that it's the most appropriate answer and if you also agree that it would be OK for me to automatically reply to this message with this answer, please click <%= link_to "here", automatic_answer_path(@top_answer) %></font>
<br /><br /><br />
<% if @ordered_answers.size > 1 %>
  <font size="4">Here are other possible answers, ranked from most suitable to least suitable for this message <em><%= @message.body %></em>:
  <br /><br />
  <ul>
  <% @ordered_answers.each do |answer| %>
    <li><font size="3"><em><%= link_to "#{answer.reply}", answer_path(answer) %></em></font>&nbsp;&nbsp;<font size="2">(Upvotes: <%= answer.upvotes %>)</font></li>
    <br />
  <% end %>
  </ul>
<% else %>
    I wasn't able to find any other possible answers to this intent.
<% end %>
</font>