config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    member do
      get 'categorize'
      get 'associate'
    end
  end
  resources :answers do
    member do
      get 'automatic'
    end
  end
  resources :intents
  resources :contexts
  resources :skus
  resources :context_categories
  resources :conversations do
    collection do
      get 'webhook'
    end
  end
  get 'static_pages/chat'

  resources :brands
  resources :products
  resources :product_types
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :users

  #get 'users/new'

  root to: 'visitors#index'
end

app/models/context_category.rb
class ContextCategory < ActiveRecord::Base
  has_many :contexts
end

app/controllers/context_categories_controller.rb
class ContextCategoriesController < ApplicationController
  before_action :set_context_category, only: [:show, :edit, :update, :destroy]

  # GET /context_categories
  # GET /context_categories.json
  def index
    @context_categories = ContextCategory.where("active = ?", true)
  end

  # GET /context_categories/1
  # GET /context_categories/1.json
  def show
  end

  # GET /context_categories/new
  def new
    @context_category = ContextCategory.new
  end

  # GET /context_categories/1/edit
  def edit
  end

  # POST /context_categories
  # POST /context_categories.json
  def create
    @context_category = ContextCategory.new(context_category_params)

    respond_to do |format|
      if @context_category.save
        format.html { redirect_to context_categories_path, notice: 'Context category was successfully created.' }
        format.json { render :show, status: :created, location: @context_category }
      else
        format.html { render :new }
        format.json { render json: @context_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /context_categories/1
  # PATCH/PUT /context_categories/1.json
  def update
    respond_to do |format|
      if @context_category.update(context_category_params)
        format.html { redirect_to context_categories_path, notice: 'Context category was successfully updated.' }
        format.json { render :show, status: :ok, location: @context_category }
      else
        format.html { render :edit }
        format.json { render json: @context_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /context_categories/1
  # DELETE /context_categories/1.json
  def destroy
    @context_category.destroy
    respond_to do |format|
      format.html { redirect_to context_categories_url, notice: 'Context category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_context_category
      @context_category = ContextCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def context_category_params
      params.require(:context_category).permit(:name, :description, :active)
    end
end

app/views/context_categories/_form.html.erb
<%= form_for(@context_category) do |f| %>
  <% if @context_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@context_category.errors.count, "error") %> prohibited this context_category from being saved:</h2>

      <ul>
      <% @context_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/context_categories/edit.html.erb
<h1>Editing Context Category</h1>
<br />
<%= render 'form' %>
<br />
<%= link_to 'Back', context_categories_path %>

app/views/context_categories/index.html.erb
<h1><%= @context_categories.size %> <%="Context Category".pluralize(@context_categories.size) %></h1>
<br />
<table>
  <thead>
    <tr>
      <th align="left" valign="top">Name</th>
      <th>&nbsp;&nbsp;&nbsp;</th>
      <th align="left" valign="top">Description</th>
      <th>&nbsp;&nbsp;&nbsp;</th>
      <th align="left" valign="top"># Contexts</th>
      <th>&nbsp;&nbsp;&nbsp;</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @context_categories.each do |context_category| %>
      <tr>
        <td valign="top"><%= link_to "#{context_category.name}", context_category %></td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td valign="top"><%= context_category.description %></td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td valign="top" align="right"><%= link_to "#{context_category.contexts.size}", context_category %></td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td valign="top">
          <%= link_to(image_tag("plus.png", :alt => "add", :title => "Add Context"), new_context_path(:context_category_id => context_category.id)) %>
        </td>
        <td valign="top">
          <%= link_to(image_tag("pencil.png", :alt => "edit", :title => "Edit Context Category"), edit_context_category_path(context_category)) %>
        </td>
        <td valign="top">
          <%= link_to(image_tag("delete.png", :alt => "delete", :title => "Delete Context Category"), context_category, method: :delete, data: { confirm: 'Are you sure?' }) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Context Category', new_context_category_path %>

app/views/context_categories/new.html.erb
<h1>New Context Category</h1>
<br />
<%= render 'form' %>
<br />
<%= link_to 'Back', context_categories_path %>

app/views/context_categories/show.html.erb
<h1>CONTEXT CATEGORY: <%= @context_category.name %></h1>
<br />
<p>
<% if @context_category.contexts.size == 0 %>
  You have not added any Contexts to this Context Category.<br /><br />
  <%= link_to "Add new Context to Context Category: #{@context_category.name}", new_context_path(:context_category_id => @context_category.id) %>
<% else %>
  <table>
  <thead>
    <tr>
      <th>Context</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Description</th>
      <th>&nbsp;&nbsp;&nbsp;</th>
      <th align="left" valign="top"># Intents</th>
      <th></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @context_category.contexts.each do |context| %>
      <tr>
        <td><%= link_to "#{context.name}", context_path(context) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= context.description %></td>
        <td>&nbsp;&nbsp;&nbsp;</td>
        <td valign="top" align="right"><%= link_to "#{context.intents.size}", context_path(context) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to(image_tag("plus.png", :alt => "add", :title => "Add intent"), new_intent_path(:context_id => context.id)) %></td>
        <td>&nbsp;</td>
        <td><%= link_to(image_tag("pencil.png", :alt => "edit", :title => "Edit context"), edit_context_path(context)) %></td>
        <td>&nbsp;</td>
        <td><%= link_to(image_tag("delete.png", :alt => "delete", :title => "Delete context"), context, method: :delete, data: { confirm: 'Are you sure?' }) %>
      </tr>
    <% end %>
  </tbody>
  </table>
  <br />
  <%= link_to "Add new Context to Context Category: #{@context_category.name}", new_context_path(:context_category_id => @context_category.id) %>
<% end %>

<br /><br /><%= link_to 'Back', context_categories_path %>