config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    member do
      get 'categorize'
      get 'associate'
    end
  end
  resources :answers do
    member do
      get 'automatic'
    end
  end
  resources :intents
  resources :contexts
  resources :skus
  resources :context_categories
  resources :conversations do
    collection do
      get 'webhook'
    end
  end
  get 'static_pages/chat'

  resources :brands
  resources :products
  resources :product_types
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resource :users

  #get 'users/new'

  root to: 'visitors#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  has_many :brands
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  has_many :products
  
  validates :name, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  def show
    @product = Product.find(params[:id])
    @brands = @product.brands
  end

  def new
    @product_type = ProductType.find(params[:product_type_id])
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product_type = ProductType.find(params[:product][:product_type_id])
    @product.product_type_id = params[:product][:product_type_id]

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product_type, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :active)
    end

end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.hidden_field :product_type_id, { value: "#{@product_type.id}" } %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows:7, cols:75 %>
  </div>
  <div class="field">
    Active <%= f.check_box :active %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>
<br />

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>
<br />
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows:7, cols:75 %>
  </div>
  <div class="field">
    Active <%= f.check_box :active %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>
<br />
<%= link_to 'Back', product_type_path(@product.product_type_id) %>

app/views/products/new.html.erb
<h1>New Product for <%= @product_type.name %></h1>
<br />
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1>PRODUCT: <%= @product.name %></h1>
<br />
<p>
<% if @brands.size == 0 %>
  You have not added any Brands to this Product.<br /><br />
  <%= link_to "Add new Brand to Product: #{@product.name}", new_brand_path(:product_id => @product.id) %>
<% else %>
  <table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
      <th>Description</th>
      <th></th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to "#{brand.name}", brand_path(brand) %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= brand.description %></td>
        <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to(image_tag("plus.png", :alt => "add", :title => "Add SKU"), new_sku_path(:brand_id => brand.id)) %></td>
        <td>&nbsp;</td>
        <td><%= link_to(image_tag("pencil.png", :alt => "edit", :title => "Edit #{brand.name}"), edit_brand_path(brand)) %></td>
        <td>&nbsp;</td>
        <td><%= link_to(image_tag("delete.png", :alt => "delete", :title => "Delete brand"), brand, method: :delete, data: { confirm: 'Are you sure?' }) %>
      </tr>
    <% end %>
  </tbody>
  </table>
  <br />
  <%= link_to "Add new Brand to Product: #{@product.name}", new_brand_path(:product_id => @product.id) %>
<% end %>

<br /><br /><%= link_to 'Back', product_type_path(@product.product_type_id) %>